name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
      
    - name: docsify-action
      uses: tool3/docsify-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}